blank_issues_enabled: false
contact_links:
  - name: shadPS4 Discord
    url: https://discord.gg/jZ38NQ3J
    about: If you need technical support with shadPS4 or have other questions the best place to ask is on the official shadPS4 Discord linked here
