# Docs - https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema
name: Bug Report
description: Report an issue with shadPS4 emulator
title: "Enter a title for the bug report here"
labels: bug
body:
  - type: textarea
    id: current_behavior
    attributes:
      label: Current Behavior
      description: "What the bug is, in a brief description"
    validations:
      required: true
      
  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: "What did you expect to happen?"
    validations:
      required: true
      
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: "How to reproduce the issue"
    validations:
      required: true
      
  - type: textarea
    id: sys_info
    attributes:
      label: System Info (Optional)
      description: "Your PC specifications. Usually only the operating system and graphics card is important. But feel free to add more info."
      placeholder: |
        Info        
        OS: Windows / Linux
        GPU: NVIDIA GeForce... / AMD RX...
      value: |
        OS: 
        GPU: 
    validations:
      required: false